FYLE-1xqdn4y
fylein/fyle-bank-feed-parser-sdk-py pull request #13
Opened 2022-01-04 05:21 UTC by Kulsekar4

2022-01-04 06:29 UTC, Code0987 requested changes

2022-01-04 06:29 UTC, Code0987 commented on card_data_parsers/parsers/cdf_parser.py
> +        txn.transaction_dt = get_iso_date_string(
Are we changing the `transaction_dt` value too?

This will make it backwards incompatible, pls do add version number changes and details in changelog.

Since this is a breaking change, pls do add test cases which have this new date field.

2022-01-04 16:38 UTC, Kulsekar4 commented on card_data_parsers/parsers/amex_parser.py
> -
don't remove this line

2022-01-05 08:18 UTC, Code0987 approved these changes

2022-01-05 08:22 UTC, Code0987 commented
@Kulsekar4 Don't forget to update the https://github.com/fylein/fyle-ccc-jobs dependency version

2022-01-05 17:08 UTC, modernwarfareuplink commented
Minor comment, lgtm 🍏 .

2022-01-05 17:09 UTC, modernwarfareuplink approved these changes

2022-01-05 17:09 UTC, modernwarfareuplink commented on CHANGELOG.md
> +## [0.5.1]
Will need to increase the minor version as this adds a new key and is not a patch(bugfix) release. 
Pls refer this link for more info - https://semver.org/

2022-01-05 17:09 UTC, modernwarfareuplink commented on setup.py
> +    version='0.5.1',
same as above

2022-01-28 04:53 UTC, gokulk16 approved these changes

2022-02-06 16:19 UTC, merged