No masking without Arguments
fylein/fyle-bank-feed-parser-sdk-py pull request #15
Opened 2022-01-24 14:23 UTC by anshsrtv

To get exact account numbers, as present in the bank feeds. Adding the condition that, if the masking arguments aren't passed to the constructor, the card numbers are masked by the parsers.

2022-01-24 14:53 UTC, Code0987 commented on card_data_parsers/parsers/amex_parser.py
> +            if account_number_mask_begin!=None and account_number_mask_end!=None:
Let's change `!= None` to `is not None`. Although it works here but `None` is not a number so we should not be doing equality check of it.

Ref: https://stackoverflow.com/a/2209781/496841

2022-01-24 15:18 UTC, Code0987 requested changes
Pls add test cases.

Idea:
- Check `card_data_parsers/amex/p1/`
- Make a duplicate folder of it and name it p2, update the args.json with null on `account_number_mask_begin` and `account_number_mask_end`
- Update expected.json as required based on data file

2022-01-25 08:57 UTC, Code0987 approved these changes
Lgtm.

Pls add version number changes before merge - example: https://github.com/fylein/fyle-bank-feed-parser-sdk-py/commit/9bbcfaa9653bbd0923f2d00ee73a35853c03b471

2022-01-25 12:02 UTC, Code0987 approved these changes

2022-01-25 14:09 UTC, modernwarfareuplink commented on card_data_parsers/parsers/vcf_parser.py
> +    def parse(file_obj, account_number_mask_begin=None, account_number_mask_end=None, default_values={}, mandatory_fields=[]) -> List[VCFTransaction]:
@anshsrtv can you create a clickup to remove using list as default parameters pls.

2022-01-25 14:14 UTC, modernwarfareuplink approved these changes

2022-01-27 05:58 UTC, Kulsekar4 approved these changes

2022-02-03 14:00 UTC, gokulk16 approved these changes

2022-02-04 08:32 UTC, merged