Updated `HappayParser` to set `foreign_amount` and `foreign_currency` to `None`, if `foreign_currency` is same as `currency`.
fylein/fyle-bank-feed-parser-sdk-py pull request #16
Opened 2022-04-08 13:27 UTC by Code0987

2022-04-08 13:30 UTC, modernwarfareuplink commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_amount and txn.foreign_currency and txn.foreign_currency != txn.currency:
Would suggest adding to all parsers @Code0987

2022-04-08 13:35 UTC, Code0987 commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_amount and txn.foreign_currency and txn.foreign_currency != txn.currency:
Apparently rest of 4 parsers have it already -

```

            if txn.foreign_currency == txn.currency and txn.foreign_amount == txn.amount:
                txn.foreign_amount = None
                txn.foreign_currency = None

2022-04-08 13:38 UTC, Code0987 commented on tests/card_data_parsers/happay/p1/expected.json
>      "bank_name": "Test Bank"
Foreign currency test below alredy

2022-04-11 10:53 UTC, modernwarfareuplink commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_amount and txn.foreign_currency and txn.foreign_currency != txn.currency:
ok, then why are we not setting the foreign_currency to None ? @Code0987

2022-04-11 10:56 UTC, Code0987 commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_amount and txn.foreign_currency and txn.foreign_currency != txn.currency:
We're settings, it's in the else part, got hidden in github view
```
            txn.foreign_amount = abs(float(txn.foreign_amount))
        else:
            txn.foreign_amount = None
            txn.foreign_currency = None

2022-04-11 10:59 UTC, modernwarfareuplink commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_amount and txn.foreign_currency and txn.foreign_currency != txn.currency:
ouch, ok missed that. Thanks !

2022-04-11 11:00 UTC, modernwarfareuplink commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_amount and txn.foreign_currency and txn.foreign_currency != txn.currency:
Also, why are we using different condition at different parsers ? Why can't we use the same condition used in other parsers ?
@Code0987

2022-04-11 11:01 UTC, Code0987 commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_amount and txn.foreign_currency and txn.foreign_currency != txn.currency:
I thought to edit the existing code present, should I just copy the conditions as-is?

2022-04-11 11:54 UTC, modernwarfareuplink commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_currency == txn.currency and txn.foreign_amount == txn.amount:
if the amount / foreign_amount are float, we will face floating point precision issue, 

can we use something like this `abs(txn.foreign_amount - txn.amount:) < 0.002` , We use this in our fyle-api and fyle-eventhandler too.

2022-04-11 11:54 UTC, modernwarfareuplink commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_currency == txn.currency and txn.foreign_amount == txn.amount:
@Code0987

2022-04-11 12:10 UTC, Code0987 commented on card_data_parsers/parsers/happay_parser.py
> +        if txn.foreign_currency == txn.currency and txn.foreign_amount == txn.amount:
Updated

2022-04-11 12:57 UTC, Code0987 commented on card_data_parsers/utils.py
> +    if date_string != '':
lint

2022-04-12 04:24 UTC, gokulk16 approved these changes

2022-04-13 08:14 UTC, modernwarfareuplink commented on card_data_parsers/parsers/amex_parser.py
> +            if txn.foreign_currency is None or (txn.foreign_currency == txn.currency and are_amounts_null_or_same(txn.foreign_amount, txn.amount)):
also, to check for `txn.foreign_amount is None`

2022-04-13 08:28 UTC, modernwarfareuplink commented on card_data_parsers/utils.py
> +        elif a == '':
should this be else ?

2022-04-13 08:54 UTC, Code0987 commented on card_data_parsers/parsers/amex_parser.py
> +            if txn.foreign_currency is None or (txn.foreign_currency == txn.currency and are_amounts_null_or_same(txn.foreign_amount, txn.amount)):
Updated

2022-04-14 08:39 UTC, modernwarfareuplink commented on card_data_parsers/utils.py
> +    if date_string != '':
FYI: Do not use `is` or `is not` comparison when we need to check for None or if both objects point to same location.

Do not use it for comparing strings or number, it might cause issue @Code0987 . The linter is correct.

2022-04-14 09:00 UTC, modernwarfareuplink commented on card_data_parsers/utils.py
> +def are_amounts_null_or_same(a, b):
null -> empty (because they could be None or '') ?

Open for other better names too @Code0987

2022-04-14 09:06 UTC, modernwarfareuplink commented on tests/card_data_parsers/happay/p1/expected.json
> -    "foreign_amount": 624.0,
Do you want to add tests with 
1. foreign_amount as None / empty string
2. foreign_currency as None / empty string
3. currency and foreign_currency as same
4. currency and foreign_currency diff as 0.001
5. currency and foreign_currency diff as 0.003

2022-04-14 09:07 UTC, modernwarfareuplink commented on CHANGELOG.md
> +- Updated parsers to set `foreign_amount` and `foreign_currency` to `None`, if `foreign_currency` is same as `currency` and `foreign_amount` is same as `amount`.
and if anyone of `foreign_amount` and `foreign_currency` is None, will set both to None

2022-04-14 09:07 UTC, modernwarfareuplink requested changes
Few comments @Code0987

2022-04-14 10:09 UTC, Code0987 commented on tests/card_data_parsers/happay/p1/expected.json
> -    "foreign_amount": 624.0,
Added all cases :)

2022-04-14 10:09 UTC, Code0987 commented
> Few comments @Code0987

Updated

2022-04-17 10:40 UTC, Kulsekar4 commented on card_data_parsers/utils.py
> +def are_amounts_empty_or_same(a, b):
the function name is conveying two many things.
p2: can have different function name like `are_amounts_valid` and have both logics or having two function like `are_amounts_empty` and `are_amounts_same`

2022-04-18 11:21 UTC, modernwarfareuplink approved these changes
1. If foreign_currency and currency are same, we can directly set the foreign_currency and foreign_amount to None. 
Reason: If currency and foreign_currency, it is wrong data and also API will throw.

2. Can alter the test case to have currency and foreign_currency as same and amounts as same/different and the result should have foreign_currency and foreign_amount is None.

2022-04-18 11:21 UTC, modernwarfareuplink commented
Pls get green from @gokulk16 on this https://github.com/fylein/fyle-bank-feed-parser-sdk-py/pull/16#pullrequestreview-944309466.

Thanks

2022-04-18 11:56 UTC, gokulk16 approved these changes

2022-04-18 11:56 UTC, gokulk16 commented on tests/card_data_parsers/happay/p1/expected.json
> -    "foreign_amount": 624.0,
Cases:
fc = hc, then fc and fa is null
fc = hc and ha=fa, then fc and fa is null
fc is null, fa is present -> both will be null
fc is present, fa is null -> both will be null
fc is null, fa is null -> do nothing

2022-04-18 16:56 UTC, merged