Parsers
fylein/fyle-bank-feed-parser-sdk-py pull request #2
Opened 2021-08-17 08:22 UTC by Code0987

2021-08-19 07:50 UTC, Kulsekar4 approved these changes
minor comments, rest lgtm

2021-08-19 07:50 UTC, Kulsekar4 commented on card_data_parsers/amex.py
> +        but maintaining min length - https://docs.python.org/2/library/string.html#string.zfill
this looks like python2, can check if this can be solved via python3
- if new library exists can update.
- if same library exists can remove or update the link

2021-08-19 07:50 UTC, Kulsekar4 commented on card_data_parsers/transaction.py
> +    orig_currency: Optional[str]
for all parser, can say what are these keys with a comment, so the other user can easily grab, 
- sync_type we use for internal usage, now since this is with a parser external user might not need it.
- orig_amount and orig_currency can have a code comment to understand better.

2021-08-20 07:09 UTC, Code0987 commented on card_data_parsers/amex.py
> +        but maintaining min length - https://docs.python.org/2/library/string.html#string.zfill
Updates

2021-08-20 08:31 UTC, Code0987 commented on card_data_parsers/transaction.py
> +    orig_currency: Optional[str]
Removed sync_type and added doc string comments

2021-08-31 16:47 UTC, jayachandhar requested changes

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/models/transaction.py
> +class Transaction(TypedDict):
use dataclass

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +logger = logging.getLogger('amex')
have a log.py and initialise log format and set logging level from there, 
getLogger('amex') -> getLogger(__name__)

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __process_amount(amount, decimal_place_indicator):
__extract_amount

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __process_currency(currency):
rename to __extract_currency

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __process_transaction_type(sign_indicator):
rename to __extract_transaction_type

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __process_lodging_transaction(txn):
not required

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __process_car_rental_transaction(txn):
not required

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __process_transaction(txn, account_number_mask_begin, account_number_mask_end):
not required

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __extract_transaction_fields(transaction):
transaction -> transaction_line

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __extract_transaction_fields(transaction):
follow same method contract __extract_transaction_fields(txn, txn_line)

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +        txn['decimal_place_indicator'] = transaction[768:769].strip()
use local variable

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +        txn['currency'] = transaction[769:772].strip()
__extract_currency(transaction[769:772].strip())

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +        txn['amount'] = transaction[737:752].strip()
__extract__amount(transaction[737:752].strip())

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +        txn['transaction_dt'] = transaction[588:598].strip()
get_iso_date_string(transaction[588:598].strip())

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +        txn['lodging_check_in_date'] = line_item[1236:1246].strip()
get_iso_date_string(line_item[1236:1246].strip(), '%Y-%m-%d')

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +            txns.append(AmexTransaction(**txn))
any reason for not using `amex_txn = AmexTransaction()` at start of this method and passing amex_txn obj to extract methods ?

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +        trxns = AmexParser.__process_transaction_lines(
return AmexParser.__process_transaction_lines(

2021-08-31 16:47 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +        txns = []
txns -> amex_txns

2021-08-31 16:48 UTC, jayachandhar commented on card_data_parsers/__init__.py
> +from .models import *
suggestion: move models and parsers to top level and have utils.py inside parsers module

2021-08-31 16:50 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __init__(self):
__init__ not required

2021-08-31 17:03 UTC, jayachandhar requested changes

2021-08-31 17:03 UTC, jayachandhar commented on card_data_parsers/parsers/cdf_parser.py
> +    def __get_element_by_tag(root, name):
each time we are traversing through a XML object to find an element
why not convert xml to dict or json ?

2021-09-02 14:05 UTC, Code0987 commented on card_data_parsers/parsers/cdf_parser.py
> +    def __get_element_by_tag(root, name):
We're also getting attributes, it'll become complex with XML element value and attribs

2021-09-02 14:08 UTC, Code0987 commented on card_data_parsers/parsers/amex_parser.py
> +        txns = []
It should be fine, like we've dedicated parsers, each doing single thing only.

2021-09-02 14:11 UTC, Code0987 commented on card_data_parsers/__init__.py
> +from .models import *
It'll be all scattered in top-level then, file-wise? Not sure

2021-09-09 07:42 UTC, jayachandhar commented on card_data_parsers/parsers/amex_parser.py
> +    def __extract_transaction_fields(transaction, default_values):
transaction -> transaction_line

2021-09-09 09:41 UTC, merged