Amount parse issue in VCF parser
fylein/fyle-bank-feed-parser-sdk-py pull request #8
Opened 2021-11-15 07:45 UTC by Code0987

2021-11-16 11:49 UTC, Code0987 commented on tests/card_data_parsers/vcf/p2/data
> +4	20203521140738 00003	1234123412341234   	0016473720000000000000000               	11122021	12012020	00000000	12012025	3	0000000000150000	3	03012021	0000000000000000	1	4798510056648351
Rename other values also

2021-11-16 12:23 UTC, modernwarfareuplink approved these changes

2021-11-17 04:00 UTC, gokulk16 requested changes

2021-11-17 04:00 UTC, gokulk16 commented on tests/card_data_parsers/vcf/p2/data
> +4	20203521140738 00003	1234123412341234   	0016473720000000000000000               	11122021	12012020	00000000	12012025	3	0000000000150000	3	03012021	0000000000000000	1	4798510056648351
+1

2021-11-17 13:24 UTC, Code0987 commented on tests/card_data_parsers/vcf/p2/data
> +4	20203521140738 00003	1234123412341234   	0016473720000000000000000               	11122021	12012020	00000000	12012025	3	0000000000150000	3	03012021	0000000000000000	1	4798510056648351
Updated

2021-11-18 05:30 UTC, jayachandhar approved these changes

2021-11-18 07:32 UTC, merged